version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build-from-docker:
    docker:
      - image: adematti/cosmopipe:dev
    steps:
      - run:
          name: CPU info
          command: cat /proc/cpuinfo
      - checkout
      - run:
          name: Tests
          no_output_timeout: 30m
          command: |
              export PYTHONPATH=$(pwd):${PYTHONPATH}
              coverage run -a -m pytest .
              coveralls
              ./codecov-upload.sh

workflows:
  main:
    jobs:
      - build-from-docker
